### ISSUE TITLE
Would like to know more about this ;)

### ISSUE THREAD

**Issue by stvnmbr1** [geckse/hydroponic-iot-app#1]

**Comment by geckse** [comment]
@stvnmbr1 
currently bootstrapping the project. I'll start soon to provide more information and code about it. 
Ofc. open source ;))

But have a sneak peak of the latest commit:
![Bildschirmfoto 2019-09-17 um 00 40 32](https://user-images.githubusercontent.com/12199921/64998288-cffab280-d8e3-11e9-90a5-7c07e1872a1a.png)

**Comment by stvnmbr1** [comment]
looking at reef-pi as hydro controller 2. new improvements include ph
control, maybe u should check it out ;)

Op di 17 sep. 2019 om 00:41 schreef Marcel Claus <notifications@github.com>:
